server:
  port: 8080
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
file:
  upload-dir: ../
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_projeto_piloto?createDatabaseIfNotExist=true
    username: root
    password: 930525
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true
  springdoc:
    pathsToMatch:
      /auth/**
      /api/**/v1/**
    swagger-ui:
      use-root-path: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
